import Mathlib.SetTheory.Cardinal.Order
import Mathlib.Data.Fintype.Card
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Data.Set.Card
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Finset.Image
import Lean.Elab.Tactic.Omega

namespace FiniteAsdim

section WellOrderedColoring
variable {V : Type*} [LinearOrder V] [WellFoundedLT V]
variable {q : ℕ}

private theorem exists_avoiding (B : Finset (Fin q)) (hB : B.card < q) :
    ∃ a : Fin q, a ∉ B := by
  classical
  have hlt : B.card < (Finset.univ : Finset (Fin q)).card := by simpa using hB
  obtain ⟨a, _, ha⟩ := Finset.exists_mem_notMem_of_card_lt_card hlt
  exact ⟨a, ha⟩

private noncomputable def chooseAvoiding (B : Finset (Fin q)) (hB : B.card < q) : Fin q :=
  Classical.choose (exists_avoiding B hB)

private lemma chooseAvoiding_notMem (B : Finset (Fin q)) (hB : B.card < q) :
    chooseAvoiding B hB ∉ B := Classical.choose_spec (exists_avoiding B hB)

private noncomputable def priorColors (hq : 0 < q) (N : V → Finset V)
    (v : V) (f : ∀ w : V, w < v → Fin q) : Finset (Fin q) := by
  classical
  exact (N v).image (fun w => if hw : w < v then f w hw else ⟨0, hq⟩)

omit [WellFoundedLT V] in
private lemma priorColors_card (hq : 0 < q) (N : V → Finset V)
    (v : V) (f : ∀ w : V, w < v → Fin q) :
    (priorColors hq N v f).card ≤ (N v).card := by
  classical
  exact Finset.card_image_le

private noncomputable def orderedGraphColor (hq : 0 < q) (N : V → Finset V)
    (hN : ∀ v, (N v).card < q) : V → Fin q :=
  wellFounded_lt.fix (fun v f => chooseAvoiding (priorColors hq N v f)
    ((priorColors_card hq N v f).trans_lt (hN v)))

private lemma orderedGraphColor_avoids (hq : 0 < q) (N : V → Finset V)
    (hN : ∀ v, (N v).card < q) (v w : V) (hw : w < v) (hmem : w ∈ N v) :
    orderedGraphColor hq N hN v ≠ orderedGraphColor hq N hN w := by
  classical
  have hfix : orderedGraphColor hq N hN v =
      chooseAvoiding (priorColors hq N v (fun y _ => orderedGraphColor hq N hN y))
        ((priorColors_card hq N v _).trans_lt (hN v)) := by
    apply WellFounded.fix_eq
  have hnot := chooseAvoiding_notMem
    (priorColors hq N v (fun y _ => orderedGraphColor hq N hN y))
    ((priorColors_card hq N v _).trans_lt (hN v))
  intro heq
  rw [hfix] at heq
  apply hnot
  rw [heq]
  unfold priorColors
  apply Finset.mem_image.mpr
  exact ⟨w, hmem, by simp [hw]⟩

end WellOrderedColoring

/-- Every graph of uniformly bounded finite degree has finitely many proper colors.
The vertex type is arbitrary; the proof uses a well-order and greedy recursion. -/
theorem bounded_degree_coloring {V : Type*} (adj : V → V → Prop)
    (hsymm : ∀ v w, adj v w → adj w v)
    (hirr : ∀ v, ¬adj v v) (D : ℕ)
    (hdegree : ∀ v, ∃ N : Finset V, (∀ w, adj v w ↔ w ∈ N) ∧ N.card ≤ D) :
    ∃ c : V → Fin (D + 1), ∀ v w, adj v w → c v ≠ c w := by
  classical
  obtain ⟨order, hwf⟩ := exists_wellFoundedLT V
  letI := order
  letI := hwf
  choose N hadj hcard using hdegree
  have hN : ∀ v, (N v).card < D + 1 := fun v => by have := hcard v; omega
  refine ⟨orderedGraphColor (by omega) N hN, ?_⟩
  intro v w h
  rcases lt_trichotomy v w with hvw | heq | hwv
  · exact Ne.symm (orderedGraphColor_avoids (by omega) N hN w v hvw
      ((hadj w v).mp (hsymm v w h)))
  · subst w
    exact (hirr v h).elim
  · exact orderedGraphColor_avoids (by omega) N hN v w hwv ((hadj v w).mp h)

private lemma encard_finite_iUnion {I X : Type*} (s : Finset I) (A : I → Set X) :
    (⋃ i ∈ s, A i).encard ≤ ∑ i ∈ s, (A i).encard := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert i s hi ih =>
    have heq : (⋃ j ∈ insert i s, A j) = A i ∪ (⋃ j ∈ s, A j) := by
      ext x
      simp
    rw [heq, Finset.sum_insert hi]
    exact (Set.encard_union_le _ _).trans (add_le_add (le_refl _) ih)
/-- Auxiliary graph generated by finitely many pairs of bounded-to-one maps. -/
def pairGraph {I X : Type*} (f g : I → X → X) (x y : X) : Prop :=
  x ≠ y ∧ ∃ i z, (f i z = x ∧ g i z = y) ∨ (g i z = x ∧ f i z = y)

/-- A finite list of pairs of bounded-to-one maps admits one finite proper coloring. -/
theorem fiber_pair_graph_coloring {I X : Type*} [Fintype I] (f g : I → X → X)
    (hf : ∀ i, ∃ k : ℕ, ∀ x, ((f i) ⁻¹' {x}).encard ≤ (k : ℕ∞))
    (hg : ∀ i, ∃ k : ℕ, ∀ x, ((g i) ⁻¹' {x}).encard ≤ (k : ℕ∞)) :
    ∃ q : ℕ, 0 < q ∧ ∃ c : X → Fin q,
      ∀ x y, pairGraph f g x y → c x ≠ c y := by
  classical
  choose kf hkf using hf
  choose kg hkg using hg
  let D := ∑ i, (kf i + kg i)
  have hdeg : ∀ x, {y | pairGraph f g x y}.encard ≤ (D : ℕ∞) := by
    intro x
    let A : I → Set X := fun i =>
      (g i '' ((f i) ⁻¹' {x})) ∪ (f i '' ((g i) ⁻¹' {x}))
    have hA : ∀ i, (A i).encard ≤ ((kf i + kg i : ℕ) : ℕ∞) := by
      intro i
      dsimp [A]
      calc
        _ ≤ (g i '' ((f i) ⁻¹' {x})).encard +
          (f i '' ((g i) ⁻¹' {x})).encard := Set.encard_union_le _ _
        _ ≤ ((f i) ⁻¹' {x}).encard + ((g i) ⁻¹' {x}).encard :=
          add_le_add (Set.encard_image_le _ _) (Set.encard_image_le _ _)
        _ ≤ (kf i : ℕ∞) + (kg i : ℕ∞) := add_le_add (hkf i x) (hkg i x)
        _ = ((kf i + kg i : ℕ) : ℕ∞) := by simp
    have hsub : {y | pairGraph f g x y} ⊆ ⋃ i, A i := by
      rintro y ⟨_, i, z, h | h⟩
      · exact Set.mem_iUnion.mpr ⟨i, Or.inl ⟨z, h.1, h.2⟩⟩
      · exact Set.mem_iUnion.mpr ⟨i, Or.inr ⟨z, h.1, h.2⟩⟩
    calc
      _ ≤ (⋃ i, A i).encard := Set.encard_le_encard hsub
      _ ≤ ∑ i, (A i).encard := by simpa using encard_finite_iUnion Finset.univ A
      _ ≤ ∑ i, ((kf i + kg i : ℕ) : ℕ∞) := Finset.sum_le_sum (fun i _ => hA i)
      _ = (D : ℕ∞) := by dsimp [D]; rw [Nat.cast_sum]
  have hneighbors : ∀ x, ∃ N : Finset X,
      (∀ y, pairGraph f g x y ↔ y ∈ N) ∧ N.card ≤ D := by
    intro x
    have hfin := Set.finite_of_encard_le_coe (hdeg x)
    refine ⟨hfin.toFinset, fun y => (hfin.mem_toFinset).symm, ?_⟩
    have hh := hdeg x
    rw [hfin.encard_eq_coe_toFinset_card] at hh
    exact ENat.coe_le_coe.mp hh
  obtain ⟨c, hc⟩ := bounded_degree_coloring (pairGraph f g)
    (fun x y h => ⟨Ne.symm h.1, by
      rcases h.2 with ⟨i, z, h | h⟩
      · exact ⟨i, z, Or.inr ⟨h.2, h.1⟩⟩
      · exact ⟨i, z, Or.inl ⟨h.2, h.1⟩⟩⟩)
    (fun x h => h.1 rfl) D hneighbors
  exact ⟨D + 1, by omega, c, hc⟩
end FiniteAsdim





